# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "Guest", password: "password", email: "guest@gmail.com", address: "160 Spear St.", city: "San Francisco", state: "CA", zip: "94105", status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph)
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "21 Mulberry Dr.", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "8653 Saxton Ave.", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "99 Beacon Road", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "418 Shipley St.", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "7 Trusel Street", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "9105 W. Pendergast St.", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "104 Lake Street", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "54 Rocky River Avenue", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "537 Foster Ave.", city: "San Francisco", state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "185 Longfellow St. ", city: 'San Francisco', state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "8860 Warren Circle", city: 'San Francisco', state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: "80 Lawrence St. ", city: 'San Francisco', state: 'CA', zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))
User.create(username: Faker::Internet.user_name, password: "password", email: Faker::Internet.email, address: Faker::Address.street_address, city: Faker::Address.city, state: Faker::Address.state, zip: Faker::Address.zip, status: "Maybe Accepting Guests", profile: Faker::Hipster.paragraph(5))


max = User.all.last.id
Cat.create(user_id: 1, name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: 1, name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: 2, name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: 3, name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: 4, name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: 5, name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )
Cat.create(user_id: (rand(max)+1), name: Faker::Cat.name, description: Faker::Cat.breed )

# Guest's Cat Booked To Someone
Booking.create(cat_id: 1, cat_name: Cat.find_by_id(1).name, host_id: 2, host_name: User.find_by_id(2).username, owner_email: User.find_by_id(1).email, start: Faker::Date.backward(30) ,end: Faker::Date.forward(30) )
Booking.create(cat_id: 2, cat_name: Cat.find_by_id(2).name, host_id: 3, host_name: User.find_by_id(3).username, owner_email: User.find_by_id(1).email, start: Faker::Date.backward(30) ,end: Faker::Date.forward(30) )


# Cat's Booked to Guest
Booking.create(cat_id: 3, cat_name: Cat.find_by_id(3).name, host_id: 1, host_name: User.find_by_id(1).username, owner_email: User.find_by_id(2).email, start: Faker::Date.backward(30) ,end: Faker::Date.forward(30) )
Booking.create(cat_id: 4, cat_name: Cat.find_by_id(4).name, host_id: 1, host_name: User.find_by_id(1).username, owner_email: User.find_by_id(3).email, start: Faker::Date.backward(30) ,end: Faker::Date.forward(30) )
Booking.create(cat_id: 5, cat_name: Cat.find_by_id(5).name, host_id: 1, host_name: User.find_by_id(1).username, owner_email: User.find_by_id(4).email, start: Faker::Date.backward(30) ,end: Faker::Date.forward(30) )
Booking.create(cat_id: 6, cat_name: Cat.find_by_id(6).name, host_id: 1, host_name: User.find_by_id(1).username, owner_email: User.find_by_id(5).email, start: Faker::Date.backward(30) ,end: Faker::Date.forward(30) )
